### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by dodiorne** [D3Ext/AORT#12]
─$ git clone https://github.com/D3Ext/AORT 1 ⨯
Cloning into 'AORT'...
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 220 (delta 90), reused 99 (delta 60), pack-reused 72
Receiving objects: 100% (220/220), 520.95 KiB | 8.83 MiB/s, done.
Resolving deltas: 100% (120/120), done.
                                                           ┌──(kali㉿kali)-[~]
└─$ cd aort                                       
cd: no such file or directory: aort
                                                           ┌──(kali㉿kali)-[~]
└─$ cd AORT 1 ⨯
                                                           ┌──(kali㉿kali)-[~/AORT]
└─$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.27.1)
Collecting pydig
  Using cached pydig-0.4.0-py3-none-any.whl (16 kB)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.2.0)Requirement already satisfied: urllib3 in /home/kali/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.26.9)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: whois in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (0.8)
Collecting pytest-warnings
  Downloading pytest_warnings-0.3.1-py2.py3-none-any.whl (3.7 kB)
Collecting python-Wappalyzer
  Using cached python_Wappalyzer-0.3.1-py3-none-any.whl (93 kB)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (2.0.6)
Requirement already satisfied: idna<4,>=2.5 in /home/kali/.local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (from pytest-warnings->-r requirements.txt (line 7)) (6.2.5)
Collecting aioresponses
  Downloading aioresponses-0.7.3-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: aiohttp in /usr/lib/python3/dist-packages (from python-Wappalyzer->-r requirements.txt (line 8)) (3.8.1)
Collecting httpretty
  Downloading httpretty-1.1.4.tar.gz (442 kB)
     ━━━━━━━━━━━━━━━━━ 442.4/442.4 KB 10.0 MB/s eta 0:00:00  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/kali/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 14, in <module>
          from setuptools.dist import Distribution, Feature        File "/home/kali/.local/lib/python3.9/site-packages/setuptools/dist.py", line 24, in <module>
          from setuptools.depends import Require
        File "/home/kali/.local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
          from .py33compat import Bytecode
        File "/home/kali/.local/lib/python3.9/site-packages/setuptools/py33compat.py", line 54, in <module>
          unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
      AttributeError: 'HTMLParser' object has no attribute 'unescape'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
                                                           ┌──(kali㉿kali)-[~/AORT]
┌──(kali㉿kali)-[~/AORT]
└─$  1 ⨯

**Comment by D3Ext** [comment]
I'm testing it and I don't have any error, I will use a new Kali to check it

```
   AORT   git:(main) pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: pydig in /home/d3ext/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.4.0)
Collecting dnspython
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 10.0 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in /home/d3ext/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.26.12)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting whois
  Using cached whois-0.9.16-py3-none-any.whl
Requirement already satisfied: pytest-warnings in /home/d3ext/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.3.1)
Collecting python-Wappalyzer
  Downloading python_Wappalyzer-0.3.1-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.7/93.7 kB 9.7 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: pytest in /usr/lib/python3.10/site-packages (from pytest-warnings->-r requirements.txt (line 7)) (7.1.3)
Requirement already satisfied: lxml in /usr/lib/python3.10/site-packages (from python-Wappalyzer->-r requirements.txt (line 8)) (4.9.1)
Collecting httpretty
  Downloading httpretty-1.1.4.tar.gz (442 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.10/site-packages (from python-Wappalyzer->-r requirements.txt (line 8)) (4.11.1)
Requirement already satisfied: aioresponses in /usr/lib/python3.10/site-packages (from python-Wappalyzer->-r requirements.txt (line 8)) (0.7.3)
Requirement already satisfied: aiohttp in /usr/lib/python3.10/site-packages (from python-Wappalyzer->-r requirements.txt (line 8)) (3.8.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (6.0.2)
Requirement already satisfied: async_timeout<5.0,>=4.0.0a3 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/lib/python3.10/site-packages (from aiohttp->python-Wappalyzer->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.10/site-packages (from beautifulsoup4->python-Wappalyzer->-r requirements.txt (line 8)) (2.3.2.post1)
Requirement already satisfied: tomli>=1.0.0 in /usr/lib/python3.10/site-packages (from pytest->pytest-warnings->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/lib/python3.10/site-packages (from pytest->pytest-warnings->-r requirements.txt (line 7)) (1.0.0)
Requirement already satisfied: packaging in /usr/lib/python3.10/site-packages (from pytest->pytest-warnings->-r requirements.txt (line 7)) (21.3)
Requirement already satisfied: py>=1.8.2 in /usr/lib/python3.10/site-packages (from pytest->pytest-warnings->-r requirements.txt (line 7)) (1.11.0)
Requirement already satisfied: iniconfig in /usr/lib/python3.10/site-packages (from pytest->pytest-warnings->-r requirements.txt (line 7)) (1.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging->pytest->pytest-warnings->-r requirements.txt (line 7)) (3.0.9)
Building wheels for collected packages: httpretty
  Building wheel for httpretty (setup.py) ... done
  Created wheel for httpretty: filename=httpretty-1.1.4-py3-none-any.whl size=28794 sha256=26c4c4e15b3488008f3a1b833397da7da930834bca96a15cfa8c00c6ece3860e
  Stored in directory: /home/d3ext/.cache/pip/wheels/17/84/74/456da302b40f8d81976edc741ba0a04bf64fd4bb3c58aca9fb
Successfully built httpretty
Installing collected packages: whois, argparse, requests, httpretty, dnspython, python-Wappalyzer
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dirhunt 0.8.1 requires click<8, but you have click 8.1.3 which is incompatible.
Successfully installed argparse-1.4.0 dnspython-2.2.1 httpretty-1.1.4 python-Wappalyzer-0.3.1 requests-2.28.1 whois-0.9.16
```

**Comment by D3Ext** [comment]
Any update?
