### ISSUE TITLE
Failed to establish a new connection: [Errno 113] No route to host'))

### ISSUE THREAD

**Issue by kouinkouin** [D3Ext/AORT#17]
Hi,

I encounter an error when I scan a domain.
I guess the error is because the port 443 is not available for this host:
In file https://github.com/D3Ext/AORT/blob/main/AORT.py#L601, we test the URI with proto=https.
Can we try with http if the port 443 is not open? Or catch the "No route to host" exception and continue?

```
[+] Scanning most common ports on xxxxx.xx

Port 22 - OPEN
Port 80 - OPEN
Port 8000 - OPEN
Port 8080 - OPEN
```

```
[+] Looking for common backup files...

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4b7c3d3880>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxx.xx', port=443): Max retries exceeded with url: /xxxxx.sql.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b7c3d3880>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/AORT/AORT.py", line 936, in <module>
    findBackups(domain)
  File "/AORT/AORT.py", line 607, in findBackups
    r = requests.get("https://" + domain + "/" + hostname + "." + ext, verify=False)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxxxx.xx', port=443): Max retries exceeded with url: /xxxxx.sql.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b7c3d3880>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by D3Ext** [comment]
Thanks for your contribution, I'll try to fix it ASAP
