### ISSUE TITLE
Looking for github errors

### ISSUE THREAD

**Issue by Kira-stuff** [D3Ext/AORT#23]
Traceback (most recent call last):
  File "c:\GIT\AORT\AORT.py", line 940, in <module>
    wafDetector(domain)
  File "c:\GIT\AORT\AORT.py", line 221, in wafDetector
    f.write(r.text)
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21346-21348: character maps to <undefined>

**Comment by D3Ext** [comment]
Hi, at the moment I don't recommend using this tool because I haven't updated it for a long time and I will release a new version soon, it will be a toolkit, with different name, in Golang, using concurrency, more than 10 tools for different purposes and much more
