### ISSUE TITLE
Getting AttributeError: module 'dns.resolver' has no attribute 'resolve'

### ISSUE THREAD

**Issue by akisakye** [D3Ext/AORT#6]
Am getting "AttributeError: module 'dns.resolver' has no attribute 'resolve'" when running with --all

```
[+] Starting Domain Zone Transfer attack...

Traceback (most recent call last):
  File "/home/user/.local/bin/aort", line 850, in <module>
    axfr(domain)
  File "/home/user/.local/bin/aort", line 210, in axfr
    ns_answer = dns.resolver.resolve(domain, 'NS')
AttributeError: module 'dns.resolver' has no attribute 'resolve'
```
Some info about the system

```
Python version: 3.8.10
Current OS: Linux 5.10.16.3-microsoft-standard-WSL2
Internet connection: ✔
```
Version info

```
SDomDiscover v1.0 - By D3Ext
Contact me: <d3ext@proton.me>
```

**Comment by D3Ext** [comment]
As I see you're using the tool on a WSL, I haven't tested it there but I think that the problem is because the `dnspython` version is a little bit old, try installing (or upgrading) the requirements and it should work

**Comment by akisakye** [comment]
Thanks. Running dnspython ugrade worked.

`pip install dnspython --upgrade`

I then run into

```
[+] Using The Wayback Machine to discover endpoints
Traceback (most recent call last):
  File "/home/user/.local/bin/aort", line 860, in <module>
    wayback(domain)
  File "/home/user/.local/bin/aort", line 450, in wayback
    for result in results:
UnboundLocalError: local variable 'results' referenced before assignment
```
Which I resolved with
`pip install results --upgrade`

Thanks for the tool

**Comment by D3Ext** [comment]
Thank you for using it :)
