### ISSUE TITLE
add more country TLDs for whois lookup

### ISSUE THREAD

**Issue by puzanov** [D3Ext/AORT#8]
Now kz domains are not supported for whois. You can check any kz domain, for example nur.kz `python3 AORT.py -d nur.kz --all`

[+] Performing Whois lookup...                                                                         
Traceback (most recent call last):
  File "/home/puzanov/AORT/AORT.py", line 504, in whoisLookup
    w = whois.whois(domain) # Two different ways to avoid a strange error
AttributeError: module 'whois' has no attribute 'whois'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/puzanov/AORT/AORT.py", line 875, in <module>
    whoisLookup(domain)
  File "/home/puzanov/AORT/AORT.py", line 506, in whoisLookup
    w = whois.query(domain)
  File "/usr/lib/python3/dist-packages/whois/__init__.py", line 54, in query
    raise Exception('Unknown TLD: %s\n(all known TLD: %s)' % (tld, list(TLD_RE.keys())))
Exception: Unknown TLD: kz
(all known TLD: ['com', 'at', 'uk', 'pl', 'be', 'biz', 'br', 'ca', 'co', 'jp', 'co_jp', 'cz', 'de', 'eu', 'fr', 'info', 'io', 'it', 'ru', 'lv', 'me', 'mx', 'name', 'net', 'nz', 'org', 'ru_rf', 'sh', 'us'])

**Comment by D3Ext** [comment]
I will try to fix it, however the whois is done with the "whois" python library so if there is any problem I will check if the TLD isn't in the list to perform the whois query in other way
