### ISSUE TITLE
AttributeError: module 'dns.resolver' has no attribute 'resolve'

### ISSUE THREAD

**Issue by GabberLevike** [D3Ext/AORT#9]
Please cane you help me with this error .

[+] Starting Domain Zone Transfer attack...

Traceback (most recent call last):
  File "/usr/local/bin/aort", line 870, in <module>
    axfr(domain)
  File "/usr/local/bin/aort", line 216, in axfr
    ns_answer = dns.resolver.resolve(domain, 'NS')
**AttributeError: module 'dns.resolver' has no attribute 'resolve'**

**Comment by D3Ext** [comment]
In this issue (https://github.com/D3Ext/AORT/issues/6) other person had the same error, it should work for you
